### ISSUE TITLE
Create user web interface

### ISSUE THREAD

**Issue by AndreasWintherMoen** [AndreasWintherMoen/jobb#1]
I assumed there would be some sort of conirmation system where the user had to message the Twilio number first before I could send an SMS to them. But I've tried adding a phone number to the database manually and sending SMS, and that works. This means the user doesn't have to send a SMS to a scary US number first to sign up, which means we can have a UI interface which manually adds numbers to the database.

This also requires a new API endpoint for subscribing and one for unsubscribing.  

In the future the web interface can be used to customize user preferences, such as type of events or which companies you're interested in, and when you want to receive the notification (eg at time of event, 5 minutes before, 1 hour before, etc).

**Comment by AndreasWintherMoen** [comment]
I'm thinking a super simple React app with Material UI.

**Comment by Kpaubert** [comment]
Wow, a React app! Groundbreaking 👍

**Comment by AndreasWintherMoen** [comment]
> Wow, a React app! Groundbreaking 👍

![bitmoji](https://sdk.bitmoji.com/render/panel/b1888edb-68f8-4d17-a234-37c3ff262f94-34ecf193-27bc-400d-b0e0-397282d0b9a4-v1.png?transparent=1&palette=1&width=246)

**Comment by FredrikAugust** [comment]
er du blitt foreleser i algdat @AndreasWintherMoen ?

**Comment by AndreasWintherMoen** [comment]
Jeg var jo studass i algdat!

![bitmoji](https://sdk.bitmoji.com/render/panel/150136d0-bf26-4d28-bdd1-a7a5552b771e-34ecf193-27bc-400d-b0e0-397282d0b9a4-v1.png?transparent=1&palette=1&width=246)
