### ISSUE TITLE
Roadmap og issues!

### ISSUE THREAD

**Issue by FredrikAugust** [AndreasWintherMoen/jobb#10]
hei jeg heter fredrik og jeg ønsker gjerne å bidra litt :)

**Comment by AndreasWintherMoen** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/94f2aaf9-22c9-49ad-b876-73715887f6b8-34ecf193-27bc-400d-b0e0-397282d0b9a4-v1.png?transparent=1&palette=1&width=246)

**Comment by AndreasWintherMoen** [comment]
Lagt til noen issues, samt et simpelt roadmap i README: c2af377bb52e82c44071095a00c31e03aa4bd07d
