### ISSUE TITLE
Add 'offline' keyword to unsubscribe

### ISSUE THREAD

**Issue by AndreasWintherMoen** [AndreasWintherMoen/jobb#11]
Jeg vet ikke hvordan jeg ikke tenkte på det (kanskje fordi klokka var ca 3 på natta!), men når man skriver ONLINE for å subscribe, så bør kodeordet for å unsubscribe naturligvis være OFFLINE i stedet for AVSLUTT 🙄 Men nå som feilen er gjort må if-statement støtte både kodeord AVSLUTT og OFFLINE for å unsubscribe. Koden ligger i `api.py`.

**Comment by FredrikAugust** [comment]
burde markeres som **TOP PRIORITY** spør du meg 😄
