### ISSUE TITLE
Configure logging based on environment

### ISSUE THREAD

**Issue by AndreasWintherMoen** [AndreasWintherMoen/jobb#13]
To do logging in Google Cloud, we need to import the _google.cloud.logging_ library and setup a logging client. However, if this runs on localhost the app won't start. It would be very neat if we could set a development/production environment flag and only setup the GC logging client in production.

**Comment by AndreasWintherMoen** [comment]
On localhost we alsio have to run

```python
import dotenv

dotenv.load_dotenv()
```

**Comment by FredrikAugust** [comment]
This could be solved by taking a page out of the ports and adapters/clean architecture pattern and implementing something like this:

```python
# essentially an interface
class Logger:
  def log(msg: string):
    pass

  def warn(msg: string):
    pass

class GCLogger(Logger):
  # override

class StdOutLogger(Logger):
  # override

# ------

class LoggingService:
  logger = None

  def __init__(self):
    if (production):
      logger = GCLogger()
    else:
      logger = StdOutLogger()

  def log(msg: string):
    logger.log(msg)
```

Thus a new logger could also easily be implemented in the future when you migrate to web3 and log into the blockchain.
