### ISSUE TITLE
Use Oxford comma when sending SMS with more than two events

### ISSUE THREAD

**Issue by Kpaubert** [AndreasWintherMoen/jobb#23]
The current implementation of JOBB uses the Associated Press Stylebook and Briefing on Media Law for assigning commas in lists for more than 2 elements. I think the owner of this repository prefers the University of Oxford Style Guide.

Ref: https://www.facebook.com/groups/2005463466347731/

**Comment by Kpaubert** [comment]
Also, if there are 3 or more events, the second to last event will not have a closing apostrophe.

Ex: 'Event 1', 'Event 2 og 'Event 3'

**Comment by Kpaubert** [comment]
Still shook that this is labelled "wontfix"

**Comment by FredrikAugust** [comment]
I am sad, surpised**,** and devastated.

**Comment by AndreasWintherMoen** [comment]
Closed in #32
