### ISSUE TITLE
Add static typing to existing code

### ISSUE THREAD

**Issue by Kpaubert** [AndreasWintherMoen/jobb#27]
Static typing helps ensure that code runs predictably, and makes it easier for new contributors to settle into the codebase. We should also make models for unknown types, like OW-events.

**Comment by AndreasWintherMoen** [comment]
True... Will do! Sounds like a fun weekend 

![bitmoji](https://sdk.bitmoji.com/render/panel/a6631f22-27a6-451c-81e0-22429641249c-34ecf193-27bc-400d-b0e0-397282d0b9a4-v1.png?transparent=1&palette=1&width=246)
