### ISSUE TITLE
Consider formatting events sms as list

### ISSUE THREAD

**Issue by AndreasWintherMoen** [AndreasWintherMoen/jobb#31]
Assuming it's possible to add newline to sms messages, it would be nice to format an event message with more than 1 event like this:

> Påmelding åpner om 5 minutter til:
> - Paint'n Sip
> - Bedriftspresentasjon med Sopra Steria

**Comment by Kpaubert** [comment]
Did a quick lookup, and it seems like this is as easy as using '\n'. [Twilio support page discussing this](https://support.twilio.com/hc/en-us/articles/223181468-How-do-I-Add-a-Line-Break-in-my-SMS-or-MMS-Message-).
